version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_NAME=sample
      - DB_USER=sampleuser
      - DB_PASS=samplepass
    depends_on:
      - db

  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=sample
      - MYSQL_USER=sampleuser
      - MYSQL_PASSWORD=samplepass
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
